<div class="cart-item cart-item-<?= $cart_item_id; ?>">
    <div class="row">
        <div class="col-md-3 text-center">
            <img src="<?= $this->basePath('img/products/thumb/' . $product_thumbnail); ?>" alt="<?= $product_name; ?>" 
                width="100%">
        </div>
        <div class="col-md-5">
            <p><strong><?= $product_name; ?></strong></p>
            <p><?= $product_desc; ?></p>
            <p>&dollar;<?= number_format($product_price, 2); ?> each</p>
        </div>
        <div class="col-md-2">
            <p class="text-center"><?= $qty; ?></p>
        </div>
        <div class="col-md-2">
            <p class="text-center">&dollar;<?= $price; ?></p>
        </div>
    </div>
</div>