<html lang="en">
    <head>
        <title></title>
        <?php echo $this->headLink()
                        ->appendStylesheet($this->basePath('css/style.css'))
                        ->appendStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->appendStylesheet($this->basePath('css/bootstrap.min.css')) ?>
    </head>

    <body>
        <?= $this->HeaderView(); ?>
        <main class="container">
            <?= $this->content; ?>
        </main>
        <?php echo $this->inlineScript() ?>
    </body>
</html>